# Generated by Django 2.2 on 2020-03-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='addinfo',
            field=models.CharField(default='No additional info', max_length=1000),
        ),
    ]
