# Generated by Django 2.2.7 on 2020-05-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_addinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='theme',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('MECH', 'Mechanical Engineering'), ('WnCC', 'Web and Coding Club'), ('Lit', 'Literati Club')], default='CSE', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('TEE', 'T-Shirt'), ('H', 'Hoodie'), ('TRO', 'Trouser'), ('CUP', 'Cups and Mugs'), ('KC', 'Keychains')], max_length=2),
        ),
    ]
