# Generated by Django 2.2.7 on 2020-05-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200517_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('TEE', 'T-Shirt'), ('H', 'Hoodie'), ('TRO', 'Trouser'), ('CUP', 'Cups and Mugs'), ('KC', 'Keychains')], max_length=3),
        ),
    ]
