# Generated by Django 2.2.7 on 2020-05-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200527_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='theme',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('MECH', 'Mechanical Engineering'), ('WnCC', 'Web and Coding Club'), ('Lit', 'Literati Club')], max_length=4),
        ),
    ]
